// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");
var SectionList$BsReactNative = require("bs-react-native/lib/js/src/components/sectionList.js");
var TouchableHighlight$BsReactNative = require("bs-react-native/lib/js/src/components/touchableHighlight.js");

var styles = StyleSheet$BsReactNative.create({
      listContainer: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1.0),
            /* [] */0
          ]),
      row: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["white"])),
            /* :: */[
              Style$BsReactNative.justifyContent(/* Center */2),
              /* :: */[
                Style$BsReactNative.paddingHorizontal(/* Pt */Block.__(0, [15])),
                /* :: */[
                  Style$BsReactNative.paddingVertical(/* Pt */Block.__(0, [8])),
                  /* [] */0
                ]
              ]
            ]
          ]),
      rowTitleText: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [17])),
            /* :: */[
              Style$BsReactNative.fontWeight(/* _500 */1056155254),
              /* [] */0
            ]
          ]),
      rowDetailText: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [15])),
            /* :: */[
              Style$BsReactNative.color(/* String */Block.__(0, ["#888888"])),
              /* :: */[
                Style$BsReactNative.lineHeight(20),
                /* [] */0
              ]
            ]
          ]),
      separator: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.height(/* Pt */Block.__(0, [StyleSheet$BsReactNative.hairlineWidth])),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#bbbbbb"])),
              /* :: */[
                Style$BsReactNative.marginLeft(/* Pt */Block.__(0, [15])),
                /* [] */0
              ]
            ]
          ]),
      separatorHighlighted: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.height(/* Pt */Block.__(0, [StyleSheet$BsReactNative.hairlineWidth])),
            /* :: */[
              Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["rgb(217, 217, 217)"])),
              /* [] */0
            ]
          ])
    });

var component = ReasonReact.statelessComponent("RNTesterExampleList");

function renderItem(onPress) {
  return (function (param) {
      return SectionList$BsReactNative.renderItem((function (param) {
                    var item = param[/* item */0];
                    return ReasonReact.element(undefined, undefined, TouchableHighlight$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function () {
                                        return Curry._1(onPress, item);
                                      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.row), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.rowTitleText), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[item[/* title */3]])),
                                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.rowDetailText), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[item[/* description */4]]))
                                            ]))]));
                  }), param);
    });
}

function itemSeparatorComponent(param) {
  return SectionList$BsReactNative.separatorComponent((function (param) {
                return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(param[/* highlighted */0] ? styles.separatorHighlighted : styles.separator), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));
              }), param);
}

function make(components, onPress, _) {
  var sections = SectionList$BsReactNative.sections(/* array */[SectionList$BsReactNative.section(components, "components", undefined, /* () */0)]);
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.listContainer), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, SectionList$BsReactNative.make(sections, renderItem(onPress), (function (item, _) {
                                          return item[/* key */0];
                                        }), Js_primitive.some(itemSeparatorComponent), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.styles = styles;
exports.component = component;
exports.renderItem = renderItem;
exports.itemSeparatorComponent = itemSeparatorComponent;
exports.make = make;
/* styles Not a pure module */
