// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var RNTesterPage = require("./RNTesterPage.js");
var RNTesterBlock = require("./RNTesterBlock.js");

function renderExample(i, param) {
  return ReasonReact.element(String(i), undefined, RNTesterBlock.make(param[/* description */1], param[/* title */0], /* array */[Curry._1(param[/* render */2], /* () */0)]));
}

var component = ReasonReact.statelessComponent("RNTesterExampleContainer");

function make(example, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, RNTesterPage.make(example[/* title */3], undefined, undefined, /* array */[$$Array.mapi(renderExample, example[/* examples */5])]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.renderExample = renderExample;
exports.component = component;
exports.make = make;
/* component Not a pure module */
