// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");

var styles = StyleSheet$BsReactNative.create({
      container: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.borderRadius(3),
            /* :: */[
              Style$BsReactNative.borderWidth(1),
              /* :: */[
                Style$BsReactNative.borderColor(/* String */Block.__(0, ["#d6d7da"])),
                /* :: */[
                  Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#ffffff"])),
                  /* :: */[
                    Style$BsReactNative.margin(/* Pt */Block.__(0, [10])),
                    /* :: */[
                      Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [5])),
                      /* :: */[
                        Style$BsReactNative.overflow(/* Hidden */1),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]),
      titleContainer: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.borderBottomWidth(1),
            /* :: */[
              Style$BsReactNative.borderTopLeftRadius(3),
              /* :: */[
                Style$BsReactNative.borderTopRightRadius(3),
                /* :: */[
                  Style$BsReactNative.borderBottomColor(/* String */Block.__(0, ["#d6d7da"])),
                  /* :: */[
                    Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#f6f7f8"])),
                    /* :: */[
                      Style$BsReactNative.paddingHorizontal(/* Pt */Block.__(0, [10])),
                      /* :: */[
                        Style$BsReactNative.paddingVertical(/* Pt */Block.__(0, [5])),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]),
      titleText: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [14])),
            /* :: */[
              Style$BsReactNative.fontWeight(/* _500 */1056155254),
              /* [] */0
            ]
          ]),
      descriptionText: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.fontSize(/* Float */Block.__(0, [14])),
            /* [] */0
          ]),
      disclosure: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.position(/* Absolute */0),
            /* :: */[
              Style$BsReactNative.top(/* Pt */Block.__(0, [0])),
              /* :: */[
                Style$BsReactNative.right(/* Pt */Block.__(0, [0])),
                /* :: */[
                  Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
                  /* [] */0
                ]
              ]
            ]
          ]),
      disclosureIcon: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.width(/* Pt */Block.__(0, [12])),
            /* :: */[
              Style$BsReactNative.height(/* Pt */Block.__(0, [8])),
              /* [] */0
            ]
          ]),
      children: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.margin(/* Pt */Block.__(0, [10])),
            /* [] */0
          ])
    });

var comp = ReasonReact.statelessComponent("RNTesterBlock");

function make(description, title, children) {
  return /* record */[
          /* debugName */comp[/* debugName */0],
          /* reactClassInternal */comp[/* reactClassInternal */1],
          /* handedOffState */comp[/* handedOffState */2],
          /* willReceiveProps */comp[/* willReceiveProps */3],
          /* didMount */comp[/* didMount */4],
          /* didUpdate */comp[/* didUpdate */5],
          /* willUnmount */comp[/* willUnmount */6],
          /* willUpdate */comp[/* willUpdate */7],
          /* shouldUpdate */comp[/* shouldUpdate */8],
          /* render */(function () {
              var eta = View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.children), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(children);
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.container), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.titleContainer), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.titleText), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[title])),
                                        description !== undefined ? ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(styles.descriptionText), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[description])) : null
                                      ])),
                              ReasonReact.element(undefined, undefined, eta)
                            ]));
            }),
          /* initialState */comp[/* initialState */10],
          /* retainedProps */comp[/* retainedProps */11],
          /* reducer */comp[/* reducer */12],
          /* subscriptions */comp[/* subscriptions */13],
          /* jsElementWrapped */comp[/* jsElementWrapped */14]
        ];
}

exports.styles = styles;
exports.comp = comp;
exports.make = make;
/* styles Not a pure module */
