#!/usr/bin/env node

// alt version of the bash script

const fs = require("fs");
const file = process.argv[2];
const guts = fs
  .readFileSync(file)
  .toString()
  .replace(
    /require\(\"bs-react-native\//g,
    'require("reason-react-native-monorepo/bs-react-native/',
  )
  .replace(
    /from \"bs-react-native\//g,
    'from "reason-react-native-monorepo/bs-react-native/',
  )
  .replace(
    /require\(\"bs-react-native-jsx3-compat\//g,
    'require("reason-react-native-monorepo/bs-react-native-jsx3-compat/',
  )
  .replace(
    /from \"bs-react-native-jsx3-compat\//g,
    'from "reason-react-native-monorepo/bs-react-native-jsx3-compat/',
  )
  .replace(
    /require\(\"reason-react-native\//g,
    'require("reason-react-native-monorepo/reason-react-native/',
  )
  .replace(
    /from \"reason-react-native\//g,
    'from "reason-react-native-monorepo/reason-react-native/',
  )
  .replace(
    /require\(\"reason-react-navigation\//g,
    'require("reason-react-native-monorepo/reason-react-navigation/',
  )
  .replace(
    /from \"reason-react-navigation\//g,
    'from "reason-react-native-monorepo/reason-react-navigation/',
  );
fs.writeFileSync(file, guts);
