// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Image$BsReactNative = require("bs-react-native/lib/js/src/components/image.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var ImageBackground$BsReactNative = require("bs-react-native/lib/js/src/components/imageBackground.js");

var examples = /* array */[/* record */[
    /* title */"ImageBackground example",
    /* description */undefined,
    /* render */(function () {
        return ReasonReact.element(undefined, undefined, ImageBackground$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, /* `URI */[
                          4245324,
                          Image$BsReactNative.imageURISource("https://lorempixel.com/output/abstract-h-c-250-400-8.jpg", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)
                        ], Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                  Style$BsReactNative.flex(1),
                                  /* :: */[
                                    Style$BsReactNative.justifyContent(/* Center */2),
                                    /* :: */[
                                      Style$BsReactNative.alignItems(/* Center */2),
                                      /* :: */[
                                        Style$BsReactNative.height(/* Pt */Block.__(0, [400])),
                                        /* :: */[
                                          Style$BsReactNative.width(/* Pt */Block.__(0, [300])),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ])), Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                  Style$BsReactNative.flex(1),
                                  /* [] */0
                                ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                            Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#FFFFFF"])),
                                            /* :: */[
                                              Style$BsReactNative.padding(/* Pt */Block.__(0, [5])),
                                              /* [] */0
                                            ]
                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Nested text"]))]))]));
      })
  ]];

var title = "<ImageBackground>";

var exampleType = /* Multiple */0;

var description = "A very basic ImageBackground component";

var displayName = "ImageBackground";

exports.title = title;
exports.exampleType = exampleType;
exports.description = description;
exports.displayName = displayName;
exports.examples = examples;
/* ReasonReact Not a pure module */
