// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var PermissionsAndroid$BsReactNative = require("bs-react-native/lib/js/src/permissionsAndroid.js");
var TouchableNativeFeedback$BsReactNative = require("bs-react-native/lib/js/src/components/touchableNativeFeedback.js");

var component = ReasonReact.statelessComponent("PermissionsAndroidExampleContent");

function requestPermissions() {
  PermissionsAndroid$BsReactNative.request(/* SEND_SMS */17, {
          title: "Hello!",
          message: "Cool app wants to send SMS..."
        }, /* () */0).then((function (permissions) {
          console.log(permissions);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, TouchableNativeFeedback$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, requestPermissions, undefined, undefined, undefined, undefined, Js_primitive.some(TouchableNativeFeedback$BsReactNative.selectableBackground(/* () */0)), undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                            Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#03DAC5"])),
                                                            /* [] */0
                                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [20])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.textAlign(/* Center */3),
                                                                      /* :: */[
                                                                        Style$BsReactNative.fontSize(/* Float */Block.__(0, [20])),
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Get SEND_SMS permission"]))]))]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var ExampleSingle = /* module */[
  /* component */component,
  /* requestPermissions */requestPermissions,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("PermissionsAndroidExampleContent");

function requestMultiplePermissions() {
  PermissionsAndroid$BsReactNative.requestMultiple(/* :: */[
          /* SEND_SMS */17,
          /* :: */[
            /* READ_EXTERNAL_STORAGE */22,
            /* :: */[
              /* WRITE_EXTERNAL_STORAGE */23,
              /* [] */0
            ]
          ]
        ]).then((function (res) {
          console.log(res);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

function make$1() {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, TouchableNativeFeedback$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, requestMultiplePermissions, undefined, undefined, undefined, undefined, Js_primitive.some(TouchableNativeFeedback$BsReactNative.selectableBackground(/* () */0)), undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                            Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#03DAC5"])),
                                                            /* [] */0
                                                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                                    Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [20])),
                                                                    /* :: */[
                                                                      Style$BsReactNative.textAlign(/* Center */3),
                                                                      /* :: */[
                                                                        Style$BsReactNative.fontSize(/* Float */Block.__(0, [20])),
                                                                        /* [] */0
                                                                      ]
                                                                    ]
                                                                  ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Get multiple permissions"]))]))]))]));
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* subscriptions */component$1[/* subscriptions */13],
          /* jsElementWrapped */component$1[/* jsElementWrapped */14]
        ];
}

var ExampleMultiple = /* module */[
  /* component */component$1,
  /* requestMultiplePermissions */requestMultiplePermissions,
  /* make */make$1
];

var examples = /* array */[
  /* record */[
    /* title */"PermissionsAndroid",
    /* description */"Single permissions",
    /* render */(function () {
        return ReasonReact.element(undefined, undefined, make(/* array */[]));
      })
  ],
  /* record */[
    /* title */"PermissionsAndroid",
    /* description */"Multiple permissions",
    /* render */(function () {
        return ReasonReact.element(undefined, undefined, make$1(/* array */[]));
      })
  ]
];

var exampleType = /* Multiple */0;

var displayName = "PermissionsAndroid";

var title = "PermissionsAndroid";

var description = "Example of getting SEND_SMS via PermissionsAndroid (only Android)";

exports.exampleType = exampleType;
exports.displayName = displayName;
exports.title = title;
exports.description = description;
exports.ExampleSingle = ExampleSingle;
exports.ExampleMultiple = ExampleMultiple;
exports.examples = examples;
/* component Not a pure module */
