// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Alert$BsReactNative = require("bs-react-native/lib/js/src/alert.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var TouchableNativeFeedback$BsReactNative = require("bs-react-native/lib/js/src/components/touchableNativeFeedback.js");

function onButtonPress() {
  return Alert$BsReactNative.alert("Button has been pressed!", undefined, undefined, undefined, undefined, /* () */0);
}

var component = ReasonReact.statelessComponent("TouchableNativeFeedbackExampleContent");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, TouchableNativeFeedback$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(TouchableNativeFeedback$BsReactNative.selectableBackground(/* () */0)), undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                  Style$BsReactNative.backgroundColor(/* String */Block.__(0, ["#03DAC5"])),
                                                  /* [] */0
                                                ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                                          Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [20])),
                                                          /* :: */[
                                                            Style$BsReactNative.textAlign(/* Center */3),
                                                            /* :: */[
                                                              Style$BsReactNative.fontSize(/* Float */Block.__(0, [20])),
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Press the button"]))]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var ExampleContent = /* module */[
  /* component */component,
  /* make */make
];

var examples = /* array */[/* record */[
    /* title */"TouchableNativeFeedback",
    /* description */"Base example",
    /* render */(function () {
        return ReasonReact.element(undefined, undefined, make(/* array */[]));
      })
  ]];

var exampleType = /* Multiple */0;

var displayName = "TouchableNativeFeedback";

var title = "<TouchableNativeFeedback>";

var description = "Simple React Native TouchableNativeFeedback component (only Android)";

exports.onButtonPress = onButtonPress;
exports.exampleType = exampleType;
exports.displayName = displayName;
exports.title = title;
exports.description = description;
exports.ExampleContent = ExampleContent;
exports.examples = examples;
/* component Not a pure module */
