// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function pct(pct$1) {
  return Pervasives.string_of_float(pct$1) + "%";
}

exports.pct = pct;
/* No side effect */
