// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function responderHandlers(onMoveShouldSetResponder, onMoveShouldSetResponderCapture, onResponderGrant, onResponderMove, onResponderReject, onResponderRelease, onResponderTerminate, onResponderTerminationRequest, onStartShouldSetResponder, onStartShouldSetResponderCapture, param) {
  return /* record */[
          /* onMoveShouldSetResponder */onMoveShouldSetResponder,
          /* onMoveShouldSetResponderCapture */onMoveShouldSetResponderCapture,
          /* onResponderGrant */onResponderGrant,
          /* onResponderMove */onResponderMove,
          /* onResponderReject */onResponderReject,
          /* onResponderRelease */onResponderRelease,
          /* onResponderTerminate */onResponderTerminate,
          /* onResponderTerminationRequest */onResponderTerminationRequest,
          /* onStartShouldSetResponder */onStartShouldSetResponder,
          /* onStartShouldSetResponderCapture */onStartShouldSetResponderCapture
        ];
}

exports.responderHandlers = responderHandlers;
/* No side effect */
