// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function option_map(fn, opt_value) {
  if (opt_value !== undefined) {
    return Js_primitive.some(Curry._1(fn, Js_primitive.valFromOption(opt_value)));
  }
  
}

function $less$less(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

exports.option_map = option_map;
exports.$less$less = $less$less;
/* No side effect */
