// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function $less$less(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

exports.$less$less = $less$less;
/* No side effect */
