// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var UtilsRN$Rebolt = require("./private/utilsRN.js");

function alert(title, message, buttons, type_, _) {
  var msg = Js_undefined.fromOption(message);
  var transformButtons = function (xs) {
    return $$Array.map((function (param) {
                  return {
                          text: Js_undefined.fromOption(param[/* text */0]),
                          onPress: Js_undefined.fromOption(param[/* onPress */1]),
                          style: Js_undefined.fromOption(UtilsRN$Rebolt.option_map((function (x) {
                                      if (x !== 465819841) {
                                        if (x >= 942927226) {
                                          return "cancel";
                                        } else {
                                          return "destructive";
                                        }
                                      } else {
                                        return "default";
                                      }
                                    }), param[/* style */2]))
                        };
                }), $$Array.of_list(xs));
  };
  var bts = Js_undefined.fromOption(UtilsRN$Rebolt.option_map(transformButtons, buttons));
  var t_ = Js_undefined.fromOption(UtilsRN$Rebolt.option_map((function (x) {
              if (x >= 780034244) {
                if (x >= 904380375) {
                  return "plain-text";
                } else {
                  return "secure-text";
                }
              } else if (x >= 465819841) {
                return "default";
              } else {
                return "login-password";
              }
            }), type_));
  ReactNative.AlertIOS.alert(title, msg, bts, t_);
  return /* () */0;
}

function prompt(title, message, buttons, type_, defaultValue, keyboardType, _) {
  var msg = Js_undefined.fromOption(message);
  var transformButtons = function (xs) {
    return $$Array.map((function (param) {
                  return {
                          text: Js_undefined.fromOption(param[/* text */0]),
                          onPress: Js_undefined.fromOption(param[/* onPress */1]),
                          style: Js_undefined.fromOption(UtilsRN$Rebolt.option_map((function (x) {
                                      if (x !== 465819841) {
                                        if (x >= 942927226) {
                                          return "cancel";
                                        } else {
                                          return "destructive";
                                        }
                                      } else {
                                        return "default";
                                      }
                                    }), param[/* style */2]))
                        };
                }), $$Array.of_list(xs));
  };
  var bts = Js_undefined.fromOption(UtilsRN$Rebolt.option_map(transformButtons, buttons));
  var t_ = Js_undefined.fromOption(UtilsRN$Rebolt.option_map((function (x) {
              if (x >= 780034244) {
                if (x >= 904380375) {
                  return "plain-text";
                } else {
                  return "secure-text";
                }
              } else if (x >= 465819841) {
                return "default";
              } else {
                return "login-password";
              }
            }), type_));
  var def_ = Js_undefined.fromOption(defaultValue);
  var keyboardT = Js_undefined.fromOption(UtilsRN$Rebolt.option_map((function (x) {
              if (x >= 511059466) {
                if (x >= 734061261) {
                  if (x >= 965330242) {
                    if (x >= 1008346616) {
                      return "email-address";
                    } else {
                      return "decimal-pad";
                    }
                  } else if (x >= 776586867) {
                    return "twitter";
                  } else {
                    return "numeric";
                  }
                } else if (x >= 568483612) {
                  return "web-search";
                } else {
                  return "number-pad";
                }
              } else if (x >= -324562960) {
                if (x >= 217673051) {
                  if (x >= 465819841) {
                    return "default";
                  } else {
                    return "ascii-capable";
                  }
                } else if (x >= 5843823) {
                  return "url";
                } else {
                  return "name-phone-pad";
                }
              } else if (x >= -444948859) {
                return "phone-pad";
              } else {
                return "numbers-and-punctuation";
              }
            }), keyboardType));
  ReactNative.AlertIOS.prompt(title, msg, bts, t_, def_, keyboardT);
  return /* () */0;
}

exports.alert = alert;
exports.prompt = prompt;
/* react-native Not a pure module */
