// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var AnimatedRe$BsReactNative = require("./animatedRe.js");

var Animation = AnimatedRe$BsReactNative.Animation;

var CompositeAnimation = AnimatedRe$BsReactNative.CompositeAnimation;

var Easing = AnimatedRe$BsReactNative.Easing;

var Interpolation = AnimatedRe$BsReactNative.Interpolation;

var Value = AnimatedRe$BsReactNative.Value;

var ValueXY = AnimatedRe$BsReactNative.ValueXY;

var $$event = AnimatedRe$BsReactNative.$$event;

var delay = AnimatedRe$BsReactNative.delay;

var sequence = AnimatedRe$BsReactNative.sequence;

var parallel = AnimatedRe$BsReactNative.parallel;

var stagger = AnimatedRe$BsReactNative.stagger;

var loop = AnimatedRe$BsReactNative.loop;

var createAnimatedComponent = AnimatedRe$BsReactNative.createAnimatedComponent;

var Timing = AnimatedRe$BsReactNative.Timing;

var TimingXY = AnimatedRe$BsReactNative.TimingXY;

var Spring = AnimatedRe$BsReactNative.Spring;

var SpringXY = AnimatedRe$BsReactNative.SpringXY;

var Decay = AnimatedRe$BsReactNative.Decay;

var DecayXY = AnimatedRe$BsReactNative.DecayXY;

var Text = 0;

var Image = 0;

var View = 0;

var ScrollView = 0;

exports.Animation = Animation;
exports.CompositeAnimation = CompositeAnimation;
exports.Easing = Easing;
exports.Interpolation = Interpolation;
exports.Value = Value;
exports.ValueXY = ValueXY;
exports.$$event = $$event;
exports.delay = delay;
exports.sequence = sequence;
exports.parallel = parallel;
exports.stagger = stagger;
exports.loop = loop;
exports.createAnimatedComponent = createAnimatedComponent;
exports.Timing = Timing;
exports.TimingXY = TimingXY;
exports.Spring = Spring;
exports.SpringXY = SpringXY;
exports.Decay = Decay;
exports.DecayXY = DecayXY;
exports.Text = Text;
exports.Image = Image;
exports.View = View;
exports.ScrollView = ScrollView;
/* AnimatedRe-BsReactNative Not a pure module */
