// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array               = require("bs-platform/lib/js/array.js");
var Js_undefined          = require("bs-platform/lib/js/js_undefined.js");
var ReactNative           = require("react-native");
var UtilsRN$BsReactNative = require("./private/utilsRN.js");

var Animation = /* module */[];

function start(t, callback, _) {
  t.start(Js_undefined.from_opt(callback));
  return /* () */0;
}

function extrapolateString(x) {
  switch (x) {
    case 0 : 
        return "extend";
    case 1 : 
        return "clamp";
    case 2 : 
        return "identity";
    
  }
}

function interpolate(value, inputRange, outputRange, easing, extrapolate, extrapolateLeft, extrapolateRight, _) {
  var tmp = {
    inputRange: $$Array.of_list(inputRange),
    outputRange: $$Array.of_list(outputRange[1])
  };
  if (easing) {
    tmp.easing = easing[0];
  }
  var tmp$1 = UtilsRN$BsReactNative.option_map(extrapolateString, extrapolate);
  if (tmp$1) {
    tmp.extrapolate = tmp$1[0];
  }
  var tmp$2 = UtilsRN$BsReactNative.option_map(extrapolateString, extrapolateLeft);
  if (tmp$2) {
    tmp.extrapolateLeft = tmp$2[0];
  }
  var tmp$3 = UtilsRN$BsReactNative.option_map(extrapolateString, extrapolateRight);
  if (tmp$3) {
    tmp.extrapolateRight = tmp$3[0];
  }
  return value.interpolate(tmp);
}

function resetAnimation(value, callback, _) {
  value.resetAnimation(Js_undefined.from_opt(callback));
  return /* () */0;
}

function stopAnimation(value, callback, _) {
  value.stopAnimation(Js_undefined.from_opt(callback));
  return /* () */0;
}

function interpolate$1(value, inputRange, outputRange, easing, extrapolate, extrapolateLeft, extrapolateRight, _) {
  var tmp = {
    inputRange: $$Array.of_list(inputRange),
    outputRange: $$Array.of_list(outputRange[1])
  };
  if (easing) {
    tmp.easing = easing[0];
  }
  var tmp$1 = UtilsRN$BsReactNative.option_map(extrapolateString, extrapolate);
  if (tmp$1) {
    tmp.extrapolate = tmp$1[0];
  }
  var tmp$2 = UtilsRN$BsReactNative.option_map(extrapolateString, extrapolateLeft);
  if (tmp$2) {
    tmp.extrapolateLeft = tmp$2[0];
  }
  var tmp$3 = UtilsRN$BsReactNative.option_map(extrapolateString, extrapolateRight);
  if (tmp$3) {
    tmp.extrapolateRight = tmp$3[0];
  }
  return value.interpolate(tmp);
}

function animate(value, toValue, easing, duration, delay, isInteraction, useNativeDriver, onComplete, iterations, _) {
  var tmp = {
    toValue: toValue[1]
  };
  if (easing) {
    tmp.easing = easing[0];
  }
  if (duration) {
    tmp.duration = duration[0];
  }
  if (delay) {
    tmp.delay = delay[0];
  }
  if (isInteraction) {
    tmp.isInteraction = isInteraction[0];
  }
  if (useNativeDriver) {
    tmp.useNativeDriver = useNativeDriver[0];
  }
  if (onComplete) {
    tmp.onComplete = onComplete[0];
  }
  if (iterations) {
    tmp.iterations = iterations[0];
  }
  return ReactNative.Animated.timing(value, tmp);
}

var Timing = /* module */[/* animate */animate];

function animate$1(value, toValue, restDisplacementThreshold, overshootClamping, restSpeedThreshold, velocity, bounciness, speed, tension, friction, isInteraction, useNativeDriver, onComplete, iterations, _) {
  return ReactNative.Animated.spring(value, {
              toValue: toValue[1],
              restDisplacementThreshold: Js_undefined.from_opt(restDisplacementThreshold),
              overshootClamping: Js_undefined.from_opt(overshootClamping),
              restSpeedThreshold: Js_undefined.from_opt(restSpeedThreshold),
              velocity: Js_undefined.from_opt(velocity),
              bounciness: Js_undefined.from_opt(bounciness),
              speed: Js_undefined.from_opt(speed),
              tension: Js_undefined.from_opt(tension),
              friction: Js_undefined.from_opt(friction),
              isInteraction: Js_undefined.from_opt(isInteraction),
              useNativeDriver: Js_undefined.from_opt(useNativeDriver),
              onComplete: Js_undefined.from_opt(onComplete),
              iterations: Js_undefined.from_opt(iterations)
            });
}

var Spring = /* module */[/* animate */animate$1];

function animate$2(value, velocity, deceleration, isInteraction, useNativeDriver, onComplete, iterations, _) {
  var tmp = {
    velocity: velocity
  };
  if (deceleration) {
    tmp.deceleration = deceleration[0];
  }
  var tmp$1 = UtilsRN$BsReactNative.optBoolToOptJsBoolean(isInteraction);
  if (tmp$1) {
    tmp.isInteraction = tmp$1[0];
  }
  var tmp$2 = UtilsRN$BsReactNative.optBoolToOptJsBoolean(useNativeDriver);
  if (tmp$2) {
    tmp.useNativeDriver = tmp$2[0];
  }
  if (onComplete) {
    tmp.onComplete = onComplete[0];
  }
  if (iterations) {
    tmp.iterations = iterations[0];
  }
  return ReactNative.Animated.decay(value, tmp);
}

var Decay = /* module */[/* animate */animate$2];

function create(x, y) {
  return new (ReactNative.Animated.ValueXY)({
              x: x,
              y: y
            });
}

function setValue(t, x, y) {
  t.setValue({
        x: x,
        y: y
      });
  return /* () */0;
}

function setOffset(t, x, y) {
  t.setOffset({
        x: x,
        y: y
      });
  return /* () */0;
}

function animate$3(value, toValue, easing, duration, delay, isInteraction, useNativeDriver, onComplete, iterations, _) {
  var tmp = {
    toValue: toValue[1]
  };
  if (easing) {
    tmp.easing = easing[0];
  }
  if (duration) {
    tmp.duration = duration[0];
  }
  if (delay) {
    tmp.delay = delay[0];
  }
  if (isInteraction) {
    tmp.isInteraction = isInteraction[0];
  }
  if (useNativeDriver) {
    tmp.useNativeDriver = useNativeDriver[0];
  }
  if (onComplete) {
    tmp.onComplete = onComplete[0];
  }
  if (iterations) {
    tmp.iterations = iterations[0];
  }
  return ReactNative.Animated.timing(value, tmp);
}

var Timing$1 = /* module */[/* animate */animate$3];

function animate$4(value, toValue, restDisplacementThreshold, overshootClamping, restSpeedThreshold, velocity, bounciness, speed, tension, friction, isInteraction, useNativeDriver, onComplete, iterations, _) {
  return ReactNative.Animated.spring(value, {
              toValue: toValue[1],
              restDisplacementThreshold: Js_undefined.from_opt(restDisplacementThreshold),
              overshootClamping: Js_undefined.from_opt(overshootClamping),
              restSpeedThreshold: Js_undefined.from_opt(restSpeedThreshold),
              velocity: Js_undefined.from_opt(velocity),
              bounciness: Js_undefined.from_opt(bounciness),
              speed: Js_undefined.from_opt(speed),
              tension: Js_undefined.from_opt(tension),
              friction: Js_undefined.from_opt(friction),
              isInteraction: Js_undefined.from_opt(isInteraction),
              useNativeDriver: Js_undefined.from_opt(useNativeDriver),
              onComplete: Js_undefined.from_opt(onComplete),
              iterations: Js_undefined.from_opt(iterations)
            });
}

var Spring$1 = /* module */[/* animate */animate$4];

function animate$5(value, velocity, deceleration, isInteraction, useNativeDriver, onComplete, iterations, _) {
  var tmp = {
    velocity: velocity
  };
  if (deceleration) {
    tmp.deceleration = deceleration[0];
  }
  var tmp$1 = UtilsRN$BsReactNative.optBoolToOptJsBoolean(isInteraction);
  if (tmp$1) {
    tmp.isInteraction = tmp$1[0];
  }
  var tmp$2 = UtilsRN$BsReactNative.optBoolToOptJsBoolean(useNativeDriver);
  if (tmp$2) {
    tmp.useNativeDriver = tmp$2[0];
  }
  if (onComplete) {
    tmp.onComplete = onComplete[0];
  }
  if (iterations) {
    tmp.iterations = iterations[0];
  }
  return ReactNative.Animated.decay(value, tmp);
}

var Decay$1 = /* module */[/* animate */animate$5];

function loop($staropt$star, animation, _) {
  var iterations = $staropt$star ? $staropt$star[0] : -1;
  return ReactNative.Animated.loop(animation, {
              iterations: iterations
            });
}

function CompositeAnimation_000(prim) {
  prim.stop();
  return /* () */0;
}

function CompositeAnimation_002(prim) {
  prim.reset();
  return /* () */0;
}

var CompositeAnimation = [
  CompositeAnimation_000,
  start,
  CompositeAnimation_002
];

var Interpolation = [interpolate];

function Value_000(prim) {
  return new (ReactNative.Animated.Value)(prim);
}

function Value_001(prim, prim$1) {
  prim.setValue(prim$1);
  return /* () */0;
}

function Value_002(prim, prim$1) {
  prim.setOffset(prim$1);
  return /* () */0;
}

function Value_003(prim) {
  prim.flattenOffset();
  return /* () */0;
}

function Value_004(prim) {
  prim.extractOffset();
  return /* () */0;
}

function Value_005(prim, prim$1) {
  return prim.addListener(prim$1);
}

function Value_006(prim, prim$1) {
  prim.removeListener(prim$1);
  return /* () */0;
}

function Value_007(prim) {
  prim.removeAllListeners();
  return /* () */0;
}

function Value_011(prim, prim$1, prim$2) {
  prim.animate(prim$1, prim$2);
  return /* () */0;
}

function Value_012(prim) {
  prim.stopTracking();
  return /* () */0;
}

function Value_013(prim) {
  prim.track();
  return /* () */0;
}

function Value_014(prim, prim$1) {
  return ReactNative.Animated.modulo(prim, prim$1);
}

function Value_015(prim, prim$1, prim$2) {
  return ReactNative.Animated.diffClamp(prim, prim$1, prim$2);
}

function Value_016(prim, prim$1) {
  return ReactNative.Animated.add(prim, prim$1);
}

function Value_017(prim, prim$1) {
  return ReactNative.Animated.divide(prim, prim$1);
}

function Value_018(prim, prim$1) {
  return ReactNative.Animated.multiply(prim, prim$1);
}

var Value = [
  Value_000,
  Value_001,
  Value_002,
  Value_003,
  Value_004,
  Value_005,
  Value_006,
  Value_007,
  resetAnimation,
  stopAnimation,
  interpolate$1,
  Value_011,
  Value_012,
  Value_013,
  Value_014,
  Value_015,
  Value_016,
  Value_017,
  Value_018,
  Timing,
  Spring,
  Decay
];

function ValueXY_003(prim) {
  prim.flattenOffset();
  return /* () */0;
}

function ValueXY_004(prim) {
  prim.extractOffset();
  return /* () */0;
}

function ValueXY_005(prim, prim$1) {
  prim.resetAnimation(prim$1);
  return /* () */0;
}

function ValueXY_006(prim, prim$1) {
  prim.stopAnimation(prim$1);
  return /* () */0;
}

function ValueXY_007(prim, prim$1) {
  return prim.addListener(prim$1);
}

function ValueXY_008(prim, prim$1) {
  prim.removeListener(prim$1);
  return /* () */0;
}

function ValueXY_009(prim) {
  prim.removeAllListeners();
  return /* () */0;
}

function ValueXY_010(prim) {
  return prim.getLayout();
}

function ValueXY_011(prim) {
  return prim.getTranslateTransform();
}

function ValueXY_012(prim, prim$1) {
  return ReactNative.Animated.add(prim, prim$1);
}

function ValueXY_013(prim, prim$1) {
  return ReactNative.Animated.divide(prim, prim$1);
}

function ValueXY_014(prim, prim$1) {
  return ReactNative.Animated.multiply(prim, prim$1);
}

function ValueXY_015(prim) {
  return prim.x;
}

function ValueXY_016(prim) {
  return prim.y;
}

var ValueXY = [
  create,
  setValue,
  setOffset,
  ValueXY_003,
  ValueXY_004,
  ValueXY_005,
  ValueXY_006,
  ValueXY_007,
  ValueXY_008,
  ValueXY_009,
  ValueXY_010,
  ValueXY_011,
  ValueXY_012,
  ValueXY_013,
  ValueXY_014,
  ValueXY_015,
  ValueXY_016,
  Timing$1,
  Spring$1,
  Decay$1
];

function $$event(prim, prim$1) {
  return ReactNative.Animated.event(prim, prim$1);
}

function delay(prim) {
  return ReactNative.Animated.delay(prim);
}

function sequence(prim) {
  return ReactNative.Animated.sequence(prim);
}

function parallel(prim, prim$1) {
  return ReactNative.Animated.parallel(prim, prim$1);
}

function stagger(prim, prim$1) {
  return ReactNative.Animated.stagger(prim, prim$1);
}

function createAnimatedComponent(prim) {
  return ReactNative.Animated.createAnimatedComponent(prim);
}

var Timing$2 = 0;

var TimingXY = 0;

var Spring$2 = 0;

var SpringXY = 0;

var Decay$2 = 0;

var DecayXY = 0;

exports.Animation               = Animation;
exports.CompositeAnimation      = CompositeAnimation;
exports.Interpolation           = Interpolation;
exports.Value                   = Value;
exports.ValueXY                 = ValueXY;
exports.$$event                 = $$event;
exports.delay                   = delay;
exports.sequence                = sequence;
exports.parallel                = parallel;
exports.stagger                 = stagger;
exports.loop                    = loop;
exports.createAnimatedComponent = createAnimatedComponent;
exports.Timing                  = Timing$2;
exports.TimingXY                = TimingXY;
exports.Spring                  = Spring$2;
exports.SpringXY                = SpringXY;
exports.Decay                   = Decay$2;
exports.DecayXY                 = DecayXY;
/* react-native Not a pure module */
