// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function registerComponent(name, comp) {
  ReactNative.AppRegistry.registerComponent(name, comp);
  return /* () */0;
}

exports.registerComponent = registerComponent;
/* react-native Not a pure module */
