// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function currentState() {
  var currState = ReactNative.AppState.currentState;
  switch (currState) {
    case "active" : 
        return /* Active */0;
    case "background" : 
        return /* Background */1;
    default:
      return /* Inactive */2;
  }
}

exports.currentState = currentState;
/* react-native Not a pure module */
