// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function mapFileType(fileType) {
  if (fileType) {
    return "photo";
  } else {
    return "video";
  }
}

function mapGroupType(groupType) {
  switch (groupType) {
    case 0 : 
        return "All";
    case 1 : 
        return "Album";
    case 2 : 
        return "Event";
    case 3 : 
        return "Faces";
    case 4 : 
        return "Library";
    case 5 : 
        return "PhotoStream";
    case 6 : 
        return "SavedPhotos";
    
  }
}

function mapAssetType(assetType) {
  switch (assetType) {
    case 0 : 
        return "All";
    case 1 : 
        return "Videos";
    case 2 : 
        return "Photos";
    
  }
}

function saveToCameraRoll(uri, type_, _) {
  var fileType = Js_undefined.fromOption(Belt_Option.map(type_, mapFileType));
  return ReactNative.CameraRoll.saveToCameraRoll(uri, fileType).then((function (uri) {
                  return Promise.resolve(/* Ok */Block.__(0, [uri]));
                })).catch((function (error) {
                return Promise.resolve(/* Error */Block.__(1, [error]));
              }));
}

function getPhotos(first, after, $staropt$star, groupName, $staropt$star$1, mimeTypes, _) {
  var groupTypes = $staropt$star !== undefined ? $staropt$star : /* SavedPhotos */6;
  var assetType = $staropt$star$1 !== undefined ? $staropt$star$1 : /* Photos */2;
  var groupTypes$1 = mapGroupType(groupTypes);
  var assetType$1 = mapAssetType(assetType);
  var tmp = {
    first: first,
    groupTypes: groupTypes$1,
    assetType: assetType$1
  };
  if (after !== undefined) {
    tmp.after = Js_primitive.valFromOption(after);
  }
  if (groupName !== undefined) {
    tmp.groupName = Js_primitive.valFromOption(groupName);
  }
  if (mimeTypes !== undefined) {
    tmp.mimeTypes = Js_primitive.valFromOption(mimeTypes);
  }
  return ReactNative.CameraRoll.getPhotos(tmp);
}

exports.saveToCameraRoll = saveToCameraRoll;
exports.getPhotos = getPhotos;
/* react-native Not a pure module */
