// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function get(key) {
  return ReactNative.Dimensions.get(key >= -762539024 ? "window" : "screen");
}

exports.get = get;
/* react-native Not a pure module */
