// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

var bounce = ReactNative.Easing.bounce;

var circle = ReactNative.Easing.circle;

var cubic = ReactNative.Easing.cubic;

var ease = ReactNative.Easing.ease;

var exp = ReactNative.Easing.exp;

var linear = ReactNative.Easing.linear;

function poly(prim) {
  return ReactNative.Easing.poly(prim);
}

var quad = ReactNative.Easing.quad;

var sin = ReactNative.Easing.sin;

function step0(prim) {
  return ReactNative.Easing.step0(prim);
}

function step1(prim) {
  return ReactNative.Easing.step1(prim);
}

function back(prim) {
  return ReactNative.Easing.back(prim);
}

function elastic(prim) {
  return ReactNative.Easing.elastic(prim);
}

function in_(prim) {
  return ReactNative.Easing.in(prim);
}

function inOut(prim) {
  return ReactNative.Easing.inOut(prim);
}

function out(prim) {
  return ReactNative.Easing.out(prim);
}

function bezier(prim, prim$1, prim$2, prim$3) {
  return ReactNative.Easing.bezier(prim, prim$1, prim$2, prim$3);
}

exports.bounce = bounce;
exports.circle = circle;
exports.cubic = cubic;
exports.ease = ease;
exports.exp = exp;
exports.linear = linear;
exports.poly = poly;
exports.quad = quad;
exports.sin = sin;
exports.step0 = step0;
exports.step1 = step1;
exports.back = back;
exports.elastic = elastic;
exports.in_ = in_;
exports.inOut = inOut;
exports.out = out;
exports.bezier = bezier;
/* bounce Not a pure module */
