// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function openCameraDialog(videoMode, success, error) {
  ReactNative.ImagePickerIOS.openCameraDialog({
        videoMode: videoMode
      }, success, error);
  return /* () */0;
}

function openSelectDialog(showImages, showVideos, success, error) {
  ReactNative.ImagePickerIOS.openSelectDialog({
        showImages: showImages,
        showVideos: showVideos
      }, success, error);
  return /* () */0;
}

function canUseCamera(prim) {
  ReactNative.ImagePickerIOS.canUseCamera(prim);
  return /* () */0;
}

function canRecordVideos(prim) {
  ReactNative.ImagePickerIOS.canRecordVideos(prim);
  return /* () */0;
}

exports.canUseCamera = canUseCamera;
exports.canRecordVideos = canRecordVideos;
exports.openCameraDialog = openCameraDialog;
exports.openSelectDialog = openSelectDialog;
/* react-native Not a pure module */
