// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function mapKeyboardEvent(keyboardEvent) {
  switch (keyboardEvent) {
    case 0 : 
        return "keyboardWillShow";
    case 1 : 
        return "keyboardDidShow";
    case 2 : 
        return "keyboardWillHide";
    case 3 : 
        return "keyboardDidHide";
    case 4 : 
        return "keyboardWillChangeFrame";
    case 5 : 
        return "keyboardDidChangeFrame";
    
  }
}

function addListener(keyboardEvent, listener) {
  return ReactNative.Keyboard.addListener(mapKeyboardEvent(keyboardEvent), listener);
}

function removeAllListeners(keyboardEvent) {
  ReactNative.Keyboard.removeAllListeners(mapKeyboardEvent(keyboardEvent));
  return /* () */0;
}

function removeListener(keyboardEvent, listener) {
  ReactNative.Keyboard.removeListener(mapKeyboardEvent(keyboardEvent), listener);
  return /* () */0;
}

var Subscription = [(function (prim) {
      prim.remove();
      return /* () */0;
    })];

exports.addListener        = addListener;
exports.removeAllListeners = removeAllListeners;
exports.removeListener     = removeListener;
exports.Subscription       = Subscription;
/* react-native Not a pure module */
