// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function mapKeyboardEvent(keyboardEvent) {
  if (keyboardEvent >= 219719669) {
    if (keyboardEvent >= 825317622) {
      if (keyboardEvent >= 832699844) {
        return "keyboardWillChangeFrame";
      } else {
        return "keyboardWillShow";
      }
    } else if (keyboardEvent >= 703379643) {
      return "keyboardWillHide";
    } else {
      return "keyboardDidShow";
    }
  } else if (keyboardEvent >= 144710821) {
    return "keyboardDidChangeFrame";
  } else {
    return "keyboardDidHide";
  }
}

function addListener(keyboardEvent, listener) {
  return ReactNative.Keyboard.addListener(mapKeyboardEvent(keyboardEvent), listener);
}

function removeAllListeners(keyboardEvent) {
  ReactNative.Keyboard.removeAllListeners(mapKeyboardEvent(keyboardEvent));
  return /* () */0;
}

function removeListener(keyboardEvent, listener) {
  ReactNative.Keyboard.removeListener(mapKeyboardEvent(keyboardEvent), listener);
  return /* () */0;
}

function remove(_, prim) {
  prim.remove();
  return /* () */0;
}

exports.remove             = remove;
exports.addListener        = addListener;
exports.removeAllListeners = removeAllListeners;
exports.removeListener     = removeListener;
/* react-native Not a pure module */
