// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactNative = require("react-native");

function canOpenURL(url) {
  return ReactNative.Linking.canOpenURL(url).then((function (bool) {
                return Promise.resolve(bool);
              }));
}

function getInitialURL(param) {
  return ReactNative.Linking.getInitialURL().then((function (stringOrNull) {
                return Promise.resolve(stringOrNull === null ? undefined : Caml_option.some(stringOrNull));
              }));
}

exports.canOpenURL = canOpenURL;
exports.getInitialURL = getInitialURL;
/* react-native Not a pure module */
