// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function create(prim) {
  return new ReactNative.NativeEventEmitter(prim);
}

function addListener(prim, prim$1, prim$2) {
  return prim.addListener(prim$1, prim$2);
}

function removeAllListeners(prim, prim$1) {
  prim.removeAllListeners(prim$1);
  return /* () */0;
}

function removeSubscription(prim, prim$1) {
  prim.removeSubscription(prim$1);
  return /* () */0;
}

var Subscription = [(function (prim, _) {
      prim.remove();
      return /* () */0;
    })];

exports.create = create;
exports.addListener = addListener;
exports.removeAllListeners = removeAllListeners;
exports.removeSubscription = removeSubscription;
exports.Subscription = Subscription;
/* react-native Not a pure module */
