// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

var match = ReactNative.Platform.OS;

var os = match === "ios" ? /* IOS */0 : /* Android */1;

function equals(targetOs) {
  if (os !== 0) {
    if (targetOs !== 0) {
      return /* true */1;
    } else {
      return /* false */0;
    }
  } else if (targetOs !== 0) {
    return /* false */0;
  } else {
    return /* true */1;
  }
}

function select(ios, android) {
  return ReactNative.Platform.select({
              ios: ios,
              android: android
            });
}

exports.os     = os;
exports.equals = equals;
exports.select = select;
/* match Not a pure module */
