// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function get(prim) {
  return ReactNative.Settings.get(prim);
}

function set(prim) {
  ReactNative.Settings.set(prim);
  return /* () */0;
}

function watchKeys(prim, prim$1) {
  return ReactNative.Settings.watchKeys(prim, prim$1);
}

function clearWatch(prim) {
  ReactNative.Settings.clearWatch(prim);
  return /* () */0;
}

exports.get = get;
exports.set = set;
exports.watchKeys = watchKeys;
exports.clearWatch = clearWatch;
/* react-native Not a pure module */
