// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Style$BsReactNative = require("./style.js");
var Animated$BsReactNative = require("./animated.js");
var AnimatedRe$BsReactNative = require("./animatedRe.js");

Style$BsReactNative.Transform[/* makeAnimated */1](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(AnimatedRe$BsReactNative.Value[/* add */16](Curry._1(Animated$BsReactNative.Value[/* create */0], -1), AnimatedRe$BsReactNative.Value[/* multiply */18](Curry._1(Animated$BsReactNative.Value[/* create */0], -1), Curry._1(Animated$BsReactNative.Value[/* create */0], -1)))), undefined, undefined, /* () */0);

/*  Not a pure module */
