// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Style = require("./style.js");
var AnimatedRe = require("./animatedRe.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

Style.Transform[/* makeAnimated */1](undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(AnimatedRe.Value[/* add */16](AnimatedRe.Value[/* create */0](-1), AnimatedRe.Value[/* multiply */18](AnimatedRe.Value[/* create */0](-1), AnimatedRe.Value[/* create */0](-1)))), undefined, undefined, /* () */0);

/*  Not a pure module */
