// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function getGravity(g) {
  switch (g) {
    case 0 : 
        return ReactNative.ToastAndroid.BOTTOM;
    case 1 : 
        return ReactNative.ToastAndroid.CENTER;
    case 2 : 
        return ReactNative.ToastAndroid.TOP;
    
  }
}

function show(message, duration) {
  ReactNative.ToastAndroid.show(message, duration ? ReactNative.ToastAndroid.SHORT : ReactNative.ToastAndroid.LONG);
  return /* () */0;
}

function showWithGravity(message, duration, gravity) {
  ReactNative.ToastAndroid.showWithGravity(message, duration ? ReactNative.ToastAndroid.SHORT : ReactNative.ToastAndroid.LONG, getGravity(gravity));
  return /* () */0;
}

function showWithGravityAndOffset(message, duration, gravity, xOffset, yOffset) {
  ReactNative.ToastAndroid.showWithGravityAndOffset(message, duration ? ReactNative.ToastAndroid.SHORT : ReactNative.ToastAndroid.LONG, getGravity(gravity), xOffset, yOffset);
  return /* () */0;
}

exports.show = show;
exports.showWithGravity = showWithGravity;
exports.showWithGravityAndOffset = showWithGravityAndOffset;
/* react-native Not a pure module */
