// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean  = require("bs-platform/lib/js/js_boolean.js");
var ReactNative = require("react-native");

function vibrate(pattern, repeat) {
  ReactNative.Vibration.vibrate(pattern, Js_boolean.to_js_boolean(repeat));
  return /* () */0;
}

function cancel() {
  ReactNative.Vibration.cancel();
  return /* () */0;
}

exports.vibrate = vibrate;
exports.cancel  = cancel;
/* react-native Not a pure module */
