// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var Text$BsReactNative = require("./text.js");
var View$BsReactNative = require("./view.js");
var Image$BsReactNative = require("./image.js");
var FlatList$BsReactNative = require("./flatList.js");
var AnimatedRe$BsReactNative = require("../animatedRe.js");
var ScrollView$BsReactNative = require("./scrollView.js");

var view = ReactNative.Animated.View;

var View = View$BsReactNative.CreateComponent(/* module */[/* view */view]);

var view$1 = ReactNative.Animated.Image;

var Image = Image$BsReactNative.CreateComponent(/* module */[/* view */view$1]);

var view$2 = AnimatedRe$BsReactNative.createAnimatedComponent(ReactNative.FlatList);

var FlatList = FlatList$BsReactNative.CreateComponent(/* module */[/* view */view$2]);

var view$3 = ReactNative.Animated.Text;

var Text = Text$BsReactNative.CreateComponent(/* module */[/* view */view$3]);

function onScrollUpdater(x, y, $staropt$star, _) {
  var $$native = $staropt$star ? $staropt$star[0] : false;
  return AnimatedRe$BsReactNative.$$event(/* array */[{
                nativeEvent: {
                  contentOffset: {
                    x: Js_undefined.fromOption(x),
                    y: Js_undefined.fromOption(y)
                  }
                }
              }], {
              useNativeDriver: $$native
            });
}

var view$4 = ReactNative.Animated.ScrollView;

var include = ScrollView$BsReactNative.CreateComponent(/* module */[/* view */view$4]);

var ScrollView_001 = /* scrollTo */include[0];

var ScrollView_002 = /* scrollToEnd */include[1];

var ScrollView_003 = /* make */include[2];

var ScrollView = /* module */[
  /* onScrollUpdater */onScrollUpdater,
  ScrollView_001,
  ScrollView_002,
  ScrollView_003
];

exports.View = View;
exports.Image = Image;
exports.Text = Text;
exports.FlatList = FlatList;
exports.ScrollView = ScrollView;
/* View Not a pure module */
