// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function make(accessibilityLabel, color, disabled, onPress, testID, title) {
  var partial_arg = {
    accessibilityLabel: Js_undefined.fromOption(accessibilityLabel),
    color: Js_undefined.fromOption(color),
    disabled: Js_undefined.fromOption(UtilsRN$BsReactNative.optBoolToOptJsBoolean(disabled)),
    onPress: Js_undefined.fromOption(onPress),
    testID: Js_undefined.fromOption(testID),
    title: Js_undefined.fromOption(title)
  };
  var partial_arg$1 = ReactNative.Button;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
