// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Props = require("../private/props.js");
var UtilsRN = require("../private/utilsRN.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");

function encodeMode(prop) {
  if (prop !== -855847923) {
    if (prop >= -281947845) {
      return "datetime";
    } else {
      return "date";
    }
  } else {
    return "time";
  }
}

function make(date, onDateChange, maximumDate, minimumDate, mode, minuteInterval, timeZoneOffsetInMinutes, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        date: date,
        onDateChange: onDateChange,
        maximumDate: maximumDate,
        minimumDate: minimumDate,
        mode: UtilsRN.option_map(encodeMode, mode),
        minuteInterval: minuteInterval,
        timeZoneOffsetInMinutes: timeZoneOffsetInMinutes
      });
  var partial_arg$1 = ReactNative.DatePickerIOS;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
