// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

var Event = /* module */[];

function make(onError, onLayout, onLoad, onLoadEnd, onLoadStart, resizeMode, source, style, imageStyle, testID, resizeMethod, accessibilityLabel, accessible, blurRadius, capInsets, defaultSource, onPartialLoad, onProgress) {
  var partial_arg = {
    onLayout: Js_undefined.fromOption(onLayout),
    onError: Js_undefined.fromOption(onError),
    onLoad: Js_undefined.fromOption(onLoad),
    onLoadEnd: Js_undefined.fromOption(onLoadEnd),
    onLoadStart: Js_undefined.fromOption(onLoadStart),
    resizeMode: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (x) {
                if (x !== -162316795) {
                  if (x >= 108828507) {
                    if (x >= 427065300) {
                      return "contain";
                    } else {
                      return "repeat";
                    }
                  } else if (x >= 98248149) {
                    return "center";
                  } else {
                    return "cover";
                  }
                } else {
                  return "stretch";
                }
              }), resizeMode)),
    source: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (x) {
                switch (x.tag | 0) {
                  case 0 : 
                  case 1 : 
                      return x[0];
                  case 2 : 
                      return $$Array.of_list(x[0]);
                  
                }
              }), source)),
    style: Js_undefined.fromOption(style),
    imageStyle: Js_undefined.fromOption(imageStyle),
    testID: Js_undefined.fromOption(testID),
    resizeMethod: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (x) {
                if (x !== -120664438) {
                  if (x >= 142301684) {
                    return "resize";
                  } else {
                    return "auto";
                  }
                } else {
                  return "scale";
                }
              }), resizeMethod)),
    accessibilityLabel: Js_undefined.fromOption(accessibilityLabel),
    accessible: Js_undefined.fromOption(UtilsRN$BsReactNative.optBoolToOptJsBoolean(accessible)),
    blurRadius: Js_undefined.fromOption(blurRadius),
    capInsets: Js_undefined.fromOption(capInsets),
    defaultSource: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (x) {
                return x[0];
              }), defaultSource)),
    onPartialLoad: Js_undefined.fromOption(onPartialLoad),
    onProgress: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (x, y) {
                return Curry._1(x, y.nativeEvent);
              }), onProgress))
  };
  var partial_arg$1 = ReactNative.ImageBackground;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.Event = Event;
exports.make = make;
/* ReasonReact Not a pure module */
