// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Props$Rebolt = require("../private/props.js");
var ReactNative = require("react-native");
var UtilsRN$Rebolt = require("../private/utilsRN.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -889544535,
    "position"
  ],
  /* tuple */[
    -797091375,
    "padding"
  ],
  /* tuple */[
    38537191,
    "height"
  ]
];

function behaviorToJs(param) {
  return Js_mapperRt.binarySearch(3, param, jsMapperConstantArray);
}

function make(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, keyboardVerticalOffset, behavior, contentContainerStyle) {
  var partial_arg = Props$Rebolt.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        keyboardVerticalOffset: Js_undefined.fromOption(keyboardVerticalOffset),
        behavior: Js_undefined.fromOption(UtilsRN$Rebolt.option_map(behaviorToJs, behavior)),
        contentContainerStyle: Js_undefined.fromOption(contentContainerStyle)
      });
  var partial_arg$1 = ReactNative.KeyboardAvoidingView;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
