// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var UtilsRN = require("../private/utilsRN.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");

function encodeAnimationType(x) {
  if (x !== -922086728) {
    if (x >= -20462287) {
      return "slide";
    } else {
      return "fade";
    }
  } else {
    return "none";
  }
}

function encodeSupportedOrientations(xs) {
  return $$Array.map((function (x) {
                if (x !== -55740357) {
                  if (x >= 923863087) {
                    if (x >= 951001435) {
                      return "portrait";
                    } else {
                      return "portrait-upside-down";
                    }
                  } else if (x >= 402056674) {
                    return "landscape-left";
                  } else {
                    return "landscape-right";
                  }
                } else {
                  return "landscape";
                }
              }), xs);
}

function make(animationType, onShow, transparent, visible, hardwareAccelerated, onRequestClose, onOrientationChange, supportedOrientations) {
  var partial_arg = {
    animationType: UtilsRN.option_map(encodeAnimationType, animationType),
    onShow: onShow,
    transparent: transparent,
    visible: visible,
    hardwareAccelerated: hardwareAccelerated,
    onRequestClose: onRequestClose,
    onOrientationChange: onOrientationChange,
    supportedOrientations: UtilsRN.option_map(encodeSupportedOrientations, supportedOrientations)
  };
  var partial_arg$1 = ReactNative.Modal;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
