// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function make(onRefresh, refreshing, colors, enabled, progressBackgroundColor, progressViewOffset, tintColor, title, titleColor, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        onRefresh: Js_undefined.fromOption(onRefresh),
        refreshing: Js_undefined.fromOption(UtilsRN$BsReactNative.optBoolToOptJsBoolean(refreshing)),
        colors: Js_undefined.fromOption(colors),
        enabled: Js_undefined.fromOption(UtilsRN$BsReactNative.optBoolToOptJsBoolean(enabled)),
        progressBackgroundColor: Js_undefined.fromOption(progressBackgroundColor),
        progressViewOffset: Js_undefined.fromOption(progressViewOffset),
        tintColor: Js_undefined.fromOption(tintColor),
        title: Js_undefined.fromOption(title),
        titleColor: Js_undefined.fromOption(titleColor)
      });
  var partial_arg$1 = ReactNative.RefreshControl;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
