// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Props = require("../private/props.js");
var UtilsRN = require("../private/utilsRN.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");

function encodeSize(size) {
  if (typeof size === "number") {
    if (size >= -9768761) {
      return "small";
    } else {
      return "large";
    }
  } else {
    var match = ReactNative.Platform.OS;
    if (match === "ios") {
      console.warn("Passing 'exact' to the size prop of activityIndicator is supported only on Android. Because you only provided the 'exact' size, we defaulted it to the small size on iOS");
      return "small";
    } else {
      return size[1];
    }
  }
}

function make(animating, color, size, hidesWhenStopped, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        animating: animating,
        color: color,
        size: UtilsRN.option_map(encodeSize, size),
        hidesWhenStopped: hidesWhenStopped
      });
  var partial_arg$1 = ReactNative.ActivityIndicator;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
