// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Props = require("../private/props.js");
var UtilsRN = require("../private/utilsRN.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");

function make(color, label, value, testID) {
  var partial_arg = {
    label: label,
    value: value,
    color: color,
    testID: testID
  };
  var partial_arg$1 = ReactNative.Picker.Item;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

var Item = /* module */[/* make */make];

function encodeMode(x) {
  if (x >= 825427144) {
    return "dialog";
  } else {
    return "dropdown";
  }
}

function make$1(onValueChange, selectedValue, enabled, mode, prompt, itemStyle, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        enabled: enabled,
        onValueChange: onValueChange,
        selectedValue: selectedValue,
        itemStyle: itemStyle,
        prompt: prompt,
        mode: UtilsRN.option_map(encodeMode, mode)
      });
  var partial_arg$1 = ReactNative.Picker;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.Item = Item;
exports.make = make$1;
/* ReasonReact Not a pure module */
