// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");
var View$BsReactNative = require("./view.js");

var view = ReactNative.SafeAreaView;

var include = View$BsReactNative.CreateComponent(/* module */[/* view */view]);

var make = include[0];

exports.make = make;
/* include Not a pure module */
