// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array               = require("bs-platform/lib/js/array.js");
var Curry                 = require("bs-platform/lib/js/curry.js");
var ReasonReact           = require("reason-react/lib/js/src/reasonReact.js");
var Js_primitive          = require("bs-platform/lib/js/js_primitive.js");
var Js_undefined          = require("bs-platform/lib/js/js_undefined.js");
var ReactNative           = require("react-native");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function jsSectionToSection(jsSection) {
  return /* record */[
          /* data */jsSection.data,
          /* key */Js_primitive.undefined_to_opt(jsSection.key),
          /* renderItem : None */0
        ];
}

function renderItem(reRenderItem, jsRenderBag) {
  return Curry._1(reRenderItem, /* record */[
              /* item */jsRenderBag.item,
              /* index */jsRenderBag.index,
              /* section */jsSectionToSection(jsRenderBag.section),
              /* separators */jsRenderBag.separators
            ]);
}

function section(data, key, renderItem, _) {
  return /* record */[
          /* data */data,
          /* key */key,
          /* renderItem */renderItem
        ];
}

function sections(reSections) {
  return $$Array.map((function (reSection) {
                return {
                        data: reSection[/* data */0],
                        key: Js_undefined.from_opt(reSection[/* key */1]),
                        renderItem: Js_undefined.from_opt(UtilsRN$BsReactNative.option_map(renderItem, reSection[/* renderItem */2]))
                      };
              }), reSections);
}

function separatorComponent(reSeparatorComponent, jsSeparatorProps) {
  return Curry._1(reSeparatorComponent, /* record */[
              /* highlighted */+jsSeparatorProps.highlighted,
              /* leadingItem */Js_primitive.undefined_to_opt(jsSeparatorProps.leadingItem),
              /* leadingSection */UtilsRN$BsReactNative.option_map(jsSectionToSection, Js_primitive.undefined_to_opt(jsSeparatorProps.leadingSection)),
              /* section */jsSectionToSection(jsSeparatorProps.section),
              /* trailingItem */Js_primitive.undefined_to_opt(jsSeparatorProps.trailingItem),
              /* trailingSection */UtilsRN$BsReactNative.option_map(jsSectionToSection, Js_primitive.undefined_to_opt(jsSeparatorProps.trailingSection))
            ]);
}

function make(sections, renderItem, keyExtractor, itemSeparatorComponent, listEmptyComponent, listFooterComponent, listHeaderComponent, sectionSeparatorComponent, extraData, initialNumToRender, onEndReached, onEndReachedThreshold, onViewableItemsChanged, onRefresh, refreshing, renderSectionHeader, renderSectionFooter, stickySectionHeadersEnabled, _children) {
  return ReasonReact.wrapJsForReason(ReactNative.SectionList, {
              sections: sections,
              renderItem: renderItem,
              keyExtractor: keyExtractor,
              ItemSeparatorComponent: Js_undefined.from_opt(itemSeparatorComponent),
              ListEmptyComponent: Js_undefined.from_opt(listEmptyComponent),
              ListFooterComponent: Js_undefined.from_opt(listFooterComponent),
              ListHeaderComponent: Js_undefined.from_opt(listHeaderComponent),
              SectionSeparatorComponent: Js_undefined.from_opt(sectionSeparatorComponent),
              extraData: Js_undefined.from_opt(extraData),
              initialNumToRender: Js_undefined.from_opt(initialNumToRender),
              onEndReached: Js_undefined.from_opt(onEndReached),
              onEndReachedThreshold: Js_undefined.from_opt(onEndReachedThreshold),
              onRefresh: Js_undefined.from_opt(onRefresh),
              onViewableItemsChanged: Js_undefined.from_opt(onViewableItemsChanged),
              refreshing: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(refreshing)),
              renderSectionHeader: Js_undefined.from_opt(renderSectionHeader),
              renderSectionFooter: Js_undefined.from_opt(renderSectionFooter),
              stickySectionHeadersEnabled: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(stickySectionHeadersEnabled))
            }, _children);
}

exports.section            = section;
exports.sections           = sections;
exports.renderItem         = renderItem;
exports.separatorComponent = separatorComponent;
exports.make               = make;
/* ReasonReact Not a pure module */
