// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array               = require("bs-platform/lib/js/array.js");
var ReasonReact           = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined          = require("bs-platform/lib/js/js_undefined.js");
var ReactNative           = require("react-native");
var Props$BsReactNative   = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function make(values, selectedIndex, onChange, enabled, momentary, tintColor, onValueChange, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        enabled: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(enabled)),
        momentary: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(momentary)),
        tintColor: Js_undefined.from_opt(tintColor),
        values: $$Array.of_list(values),
        selectedIndex: Js_undefined.from_opt(selectedIndex),
        onChange: Js_undefined.from_opt(onChange),
        onValueChange: Js_undefined.from_opt(onValueChange)
      });
  var partial_arg$1 = ReactNative.SegmentedControlIOS;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
