// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function convertImageSource(src) {
  switch (src.tag | 0) {
    case 0 : 
    case 1 : 
        return src[0];
    case 2 : 
        return $$Array.of_list(src[0]);
    
  }
}

function make(disabled, maximumTrackTintColor, maximumValue, minimumTrackTintColor, minimumValue, onSlidingComplete, onValueChange, step, value, thumbTintColor, maximumTrackImage, minimumTrackImage, thumbImage, trackImage, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        disabled: Js_undefined.fromOption(UtilsRN$BsReactNative.optBoolToOptJsBoolean(disabled)),
        maximumTrackTintColor: Js_undefined.fromOption(maximumTrackTintColor),
        maximumValue: Js_undefined.fromOption(maximumValue),
        minimumTrackTintColor: Js_undefined.fromOption(minimumTrackTintColor),
        minimumValue: Js_undefined.fromOption(minimumValue),
        onSlidingComplete: Js_undefined.fromOption(onSlidingComplete),
        onValueChange: Js_undefined.fromOption(onValueChange),
        step: Js_undefined.fromOption(step),
        value: Js_undefined.fromOption(value),
        thumbTintColor: Js_undefined.fromOption(thumbTintColor),
        maximumTrackImage: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map(convertImageSource, maximumTrackImage)),
        minimumTrackImage: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map(convertImageSource, minimumTrackImage)),
        thumbImage: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map(convertImageSource, thumbImage)),
        trackImage: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map(convertImageSource, trackImage))
      });
  var partial_arg$1 = ReactNative.Slider;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
