// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean            = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact           = require("reason-react/lib/js/src/reasonReact.js");
var Js_undefined          = require("bs-platform/lib/js/js_undefined.js");
var ReactNative           = require("react-native");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function setHidden(hidden, animation, _) {
  ReactNative.StatusBar.setHidden(Js_boolean.to_js_boolean(hidden), Js_undefined.from_opt(UtilsRN$BsReactNative.option_map((function (x) {
                  if (x !== -922086728) {
                    if (x >= -20462287) {
                      return "slide";
                    } else {
                      return "fade";
                    }
                  } else {
                    return "none";
                  }
                }), animation)));
  return /* () */0;
}

function setBarStyle(style, animated, _) {
  ReactNative.StatusBar.setBarStyle(style !== -106329341 ? (
          style >= 465819841 ? "default" : "dark-content"
        ) : "light-content", Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(animated)));
  return /* () */0;
}

function setNetworkActivityIndicatorVisible(visible) {
  ReactNative.StatusBar.setNetworkActivityIndicatorVisible(Js_boolean.to_js_boolean(visible));
  return /* () */0;
}

function setBackgroundColor(color, animated, _) {
  ReactNative.StatusBar.setBackgroundColor(color, Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(animated)));
  return /* () */0;
}

function setTranslucent(translucent) {
  ReactNative.StatusBar.setTranslucent(Js_boolean.to_js_boolean(translucent));
  return /* () */0;
}

function make(animated, barStyle, hidden, backgroundColor, translucent, networkActivityIndicatorVisible, showHideTransition) {
  var partial_arg = {
    animated: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(animated)),
    barStyle: Js_undefined.from_opt(UtilsRN$BsReactNative.option_map((function (x) {
                if (x !== -106329341) {
                  if (x >= 465819841) {
                    return "default";
                  } else {
                    return "dark-content";
                  }
                } else {
                  return "light-content";
                }
              }), barStyle)),
    backgroundColor: Js_undefined.from_opt(backgroundColor),
    hidden: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(hidden)),
    translucent: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(translucent)),
    networkActivityIndicatorVisible: Js_undefined.from_opt(UtilsRN$BsReactNative.optBoolToOptJsBoolean(networkActivityIndicatorVisible)),
    showHideTransition: Js_undefined.from_opt(UtilsRN$BsReactNative.option_map((function (x) {
                if (x !== -922086728) {
                  if (x >= -20462287) {
                    return "slide";
                  } else {
                    return "fade";
                  }
                } else {
                  return "none";
                }
              }), showHideTransition))
  };
  var partial_arg$1 = ReactNative.StatusBar;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.setHidden                          = setHidden;
exports.setBarStyle                        = setBarStyle;
exports.setNetworkActivityIndicatorVisible = setNetworkActivityIndicatorVisible;
exports.setBackgroundColor                 = setBackgroundColor;
exports.setTranslucent                     = setTranslucent;
exports.make                               = make;
/* ReasonReact Not a pure module */
