// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function make(title, badgeColor, badge, icon, onPress, renderAsOriginal, style, selected, selectedIcon, isTVSelectable, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        badgeColor: badgeColor,
        title: title,
        badge: badge,
        icon: icon,
        onPress: onPress,
        renderAsOriginal: renderAsOriginal,
        selected: selected,
        selectedIcon: selectedIcon,
        style: style,
        isTVSelectable: isTVSelectable
      });
  var partial_arg$1 = ReactNative.TabBarIOS.Item;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

var Item = /* module */[/* make */make];

function make$1(barTintColor, itemPositioning, style, tintColor, translucent, unselectedItemTintColor, unselectedTintColor, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        barTintColor: barTintColor,
        itemPositioning: UtilsRN$BsReactNative.option_map((function (x) {
                if (x !== -1011102077) {
                  if (x >= 98248149) {
                    return "center";
                  } else {
                    return "auto";
                  }
                } else {
                  return "fill";
                }
              }), itemPositioning),
        tintColor: tintColor,
        translucent: translucent,
        unselectedItemTintColor: unselectedItemTintColor,
        unselectedTintColor: unselectedTintColor
      });
  var partial_arg$1 = ReactNative.TabBarIOS;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.Item = Item;
exports.make = make$1;
/* ReasonReact Not a pure module */
