// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");
var Types$BsReactNative = require("../types.js");

function make(accessible, accessibilityLabel, accessibilityComponentType, accessibilityTraits, delayLongPress, delayPressIn, delayPressOut, disabled, hitSlop, onLayout, onLongPress, onPress, onPressIn, onPressOut, pressRetentionOffset, style, background, useForeground, testID) {
  var partial_arg = {
    accessible: accessible,
    accessibilityLabel: accessibilityLabel,
    delayLongPress: delayLongPress,
    delayPressIn: delayPressIn,
    delayPressOut: delayPressOut,
    disabled: disabled,
    hitSlop: hitSlop,
    onLayout: onLayout,
    onLongPress: onLongPress,
    onPress: onPress,
    background: background,
    onPressIn: onPressIn,
    onPressOut: onPressOut,
    pressRetentionOffset: pressRetentionOffset,
    style: style,
    useForeground: useForeground,
    accessibilityComponentType: Belt_Option.map(accessibilityComponentType, Types$BsReactNative.accessibilityComponentTypeToJs),
    accessibilityTraits: Belt_Option.map(accessibilityTraits, (function (x) {
            return $$Array.of_list(List.map(Types$BsReactNative.accessibilityTraitToJs, x));
          })),
    testID: testID
  };
  var partial_arg$1 = ReactNative.TouchableNativeFeedback;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

function selectableBackground(prim) {
  return ReactNative.TouchableNativeFeedback.SelectableBackground();
}

function selectableBackgroundBorderless(prim) {
  return ReactNative.TouchableNativeFeedback.SelectableBackgroundBorderless();
}

function canUseNativeForeground(prim) {
  return ReactNative.TouchableNativeFeedback.CanUseNativeForeground();
}

function ripple(prim, prim$1) {
  return ReactNative.TouchableNativeFeedback.Ripple(prim, prim$1);
}

exports.make = make;
exports.selectableBackground = selectableBackground;
exports.selectableBackgroundBorderless = selectableBackgroundBorderless;
exports.canUseNativeForeground = canUseNativeForeground;
exports.ripple = ripple;
/* ReasonReact Not a pure module */
