// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Props$Rebolt = require("../private/props.js");
var ReactNative = require("react-native");
var UtilsRN$Rebolt = require("../private/utilsRN.js");

function make(initialPage, keyboardDismissMode, onPageScroll, onPageScrollStateChanged, onPageSelected, pageMargin, peekEnabled, scrollEnabled, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$Rebolt.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        initialPage: Js_undefined.fromOption(initialPage),
        onPageScroll: Js_undefined.fromOption(onPageScroll),
        onPageScrollStateChanged: Js_undefined.fromOption(onPageScrollStateChanged),
        onPageSelected: Js_undefined.fromOption(onPageSelected),
        pageMargin: Js_undefined.fromOption(pageMargin),
        keyboardDismissMode: Js_undefined.fromOption(UtilsRN$Rebolt.option_map((function (param) {
                    if (param >= -453364557) {
                      return "on-drag";
                    } else {
                      return "none";
                    }
                  }), keyboardDismissMode)),
        peekEnabled: Js_undefined.fromOption(peekEnabled),
        scrollEnabled: Js_undefined.fromOption(scrollEnabled)
      });
  var partial_arg$1 = ReactNative.ViewPagerAndroid;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

function setPage(prim, prim$1) {
  prim.setPage(prim$1);
  return /* () */0;
}

exports.setPage = setPage;
exports.make = make;
/* ReasonReact Not a pure module */
