// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function make(initialPage, keyboardDismissMode, onPageScroll, onPageScrollStateChanged, onPageSelected, pageMargin, peekEnabled, scrollEnabled, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        initialPage: initialPage,
        onPageScroll: onPageScroll,
        onPageScrollStateChanged: onPageScrollStateChanged,
        onPageSelected: onPageSelected,
        pageMargin: pageMargin,
        keyboardDismissMode: UtilsRN$BsReactNative.option_map((function (param) {
                if (param >= -453364557) {
                  return "on-drag";
                } else {
                  return "none";
                }
              }), keyboardDismissMode),
        peekEnabled: peekEnabled,
        scrollEnabled: scrollEnabled
      });
  var partial_arg$1 = ReactNative.ViewPagerAndroid;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

function setPage(prim, prim$1) {
  prim.setPage(prim$1);
  return /* () */0;
}

exports.setPage = setPage;
exports.make = make;
/* ReasonReact Not a pure module */
