// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");

function make(initialPage, keyboardDismissMode, onPageScroll, onPageScrollStateChanged, onPageSelected, pageMargin, peekEnabled, scrollEnabled, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        initialPage: initialPage,
        onPageScroll: onPageScroll,
        onPageScrollStateChanged: onPageScrollStateChanged,
        onPageSelected: onPageSelected,
        pageMargin: pageMargin,
        keyboardDismissMode: Belt_Option.map(keyboardDismissMode, (function (param) {
                if (param >= -453364557) {
                  return "on-drag";
                } else {
                  return "none";
                }
              })),
        peekEnabled: peekEnabled,
        scrollEnabled: scrollEnabled
      });
  var partial_arg$1 = ReactNative.ViewPagerAndroid;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

function setPage(prim, prim$1) {
  prim.setPage(prim$1);
  return /* () */0;
}

exports.make = make;
exports.setPage = setPage;
/* ReasonReact Not a pure module */
