// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

var EventTypes = /* module */[];

function source(prim, prim$1, prim$2, prim$3, _) {
  var tmp = { };
  if (prim !== undefined) {
    tmp.uri = Js_primitive.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.method = Js_primitive.valFromOption(prim$1);
  }
  if (prim$2 !== undefined) {
    tmp.headers = Js_primitive.valFromOption(prim$2);
  }
  if (prim$3 !== undefined) {
    tmp.body = Js_primitive.valFromOption(prim$3);
  }
  return tmp;
}

function make(source, style, renderError, renderLoading, onError, onLoad, onLoadEnd, onLoadStart, automaticallyAdjustContentInsets, contentInsets, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, injectJavaScript, injectedJavaScript, mediaPlaybackRequiresUserAction, onMessage, onNavigationStateChange, scalesPageToFit, startInLoadingState, domStorageEnabled, javaScriptEnabled, mixedContentMode, thirdPartyCookiesEnabled, userAgent, allowsInlineMediaPlayback, bounces, dataDetectorTypes, decelerationRate, onShouldStartLoadWithRequest, scrollEnabled) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        source: source,
        style: style,
        automaticallyAdjustContentInsets: automaticallyAdjustContentInsets,
        contentInsets: contentInsets,
        injectJavaScript: injectJavaScript,
        injectedJavaScript: injectedJavaScript,
        mediaPlaybackRequiresUserAction: mediaPlaybackRequiresUserAction,
        onError: onError,
        onLoad: onLoad,
        onLoadEnd: onLoadEnd,
        onLoadStart: onLoadStart,
        onMessage: onMessage,
        onNavigationStateChange: onNavigationStateChange,
        renderError: renderError,
        renderLoading: renderLoading,
        scalesPageToFit: scalesPageToFit,
        startInLoadingState: startInLoadingState,
        domStorageEnabled: domStorageEnabled,
        javaScriptEnabled: javaScriptEnabled,
        mixedContentMode: UtilsRN$BsReactNative.option_map((function (contentMode) {
                var to_string = function (param) {
                  if (param !== -853883856) {
                    if (param >= 422592140) {
                      return "never";
                    } else {
                      return "always";
                    }
                  } else {
                    return "compatibility";
                  }
                };
                return $$Array.of_list(List.map(to_string, contentMode));
              }), mixedContentMode),
        thirdPartyCookiesEnabled: thirdPartyCookiesEnabled,
        userAgent: userAgent,
        allowsInlineMediaPlayback: allowsInlineMediaPlayback,
        bounces: bounces,
        dataDetectorTypes: UtilsRN$BsReactNative.option_map((function (dataDetectorType) {
                var to_string = function (param) {
                  if (param >= -922086728) {
                    if (param >= 4847905) {
                      if (param >= 487289268) {
                        return "address";
                      } else {
                        return "all";
                      }
                    } else if (param >= -119363460) {
                      return "calendarEvent";
                    } else {
                      return "none";
                    }
                  } else if (param >= -940571433) {
                    return "phoneNumber";
                  } else {
                    return "link";
                  }
                };
                return $$Array.of_list(List.map(to_string, dataDetectorType));
              }), dataDetectorTypes),
        decelerationRate: UtilsRN$BsReactNative.option_map((function (rate) {
                var to_float = function (param) {
                  if (typeof param === "number") {
                    if (param >= 812216871) {
                      return 0.998;
                    } else {
                      return 0.99;
                    }
                  } else {
                    return param[1];
                  }
                };
                return $$Array.of_list(List.map(to_float, rate));
              }), decelerationRate),
        onShouldStartLoadWithRequest: onShouldStartLoadWithRequest,
        scrollEnabled: scrollEnabled
      });
  var partial_arg$1 = ReactNative.WebView;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

function sourceUri(prim, prim$1, prim$2, prim$3, _) {
  var tmp = { };
  if (prim !== undefined) {
    tmp.uri = Js_primitive.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.method = Js_primitive.valFromOption(prim$1);
  }
  if (prim$2 !== undefined) {
    tmp.headers = Js_primitive.valFromOption(prim$2);
  }
  if (prim$3 !== undefined) {
    tmp.body = Js_primitive.valFromOption(prim$3);
  }
  return tmp;
}

function sourceHtml(prim, prim$1, _) {
  var tmp = { };
  if (prim !== undefined) {
    tmp.html = Js_primitive.valFromOption(prim);
  }
  if (prim$1 !== undefined) {
    tmp.baseUrl = Js_primitive.valFromOption(prim$1);
  }
  return tmp;
}

function goForward(prim) {
  prim.goForward();
  return /* () */0;
}

function goBack(prim) {
  prim.goBack();
  return /* () */0;
}

function reload(prim) {
  prim.reload();
  return /* () */0;
}

function stopLoading(prim) {
  prim.stopLoading();
  return /* () */0;
}

exports.EventTypes = EventTypes;
exports.sourceUri = sourceUri;
exports.sourceHtml = sourceHtml;
exports.source = source;
exports.goForward = goForward;
exports.goBack = goBack;
exports.reload = reload;
exports.stopLoading = stopLoading;
exports.make = make;
/* ReasonReact Not a pure module */
