// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var Props$BsReactNative = require("../private/props.js");
var UtilsRN$BsReactNative = require("../private/utilsRN.js");

function make(source, style, renderError, renderLoading, onError, onLoad, onLoadEnd, onLoadStart, automaticallyAdjustContentInsets, contentInsets, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, injectJavaScript, injectedJavaScript, mediaPlaybackRequiresUserAction, onMessage, onNavigationStateChange, scalesPageToFit, startInLoadingState, domStorageEnabled, javaScriptEnabled, mixedContentMode, thirdPartyCookiesEnabled, userAgent, allowsInlineMediaPlayback, bounces, dataDetectorTypes, decelerationRate, onShouldStartLoadWithRequest, scrollEnabled) {
  var partial_arg = Props$BsReactNative.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        source: Js_undefined.fromOption(source),
        style: Js_undefined.fromOption(style),
        automaticallyAdjustContentInsets: Js_undefined.fromOption(automaticallyAdjustContentInsets),
        contentInsets: Js_undefined.fromOption(contentInsets),
        injectJavaScript: Js_undefined.fromOption(injectJavaScript),
        injectedJavaScript: Js_undefined.fromOption(injectedJavaScript),
        mediaPlaybackRequiresUserAction: Js_undefined.fromOption(mediaPlaybackRequiresUserAction),
        onError: Js_undefined.fromOption(onError),
        onLoad: Js_undefined.fromOption(onLoad),
        onLoadEnd: Js_undefined.fromOption(onLoadEnd),
        onLoadStart: Js_undefined.fromOption(onLoadStart),
        onMessage: Js_undefined.fromOption(onMessage),
        onNavigationStateChange: Js_undefined.fromOption(onNavigationStateChange),
        renderError: Js_undefined.fromOption(renderError),
        renderLoading: Js_undefined.fromOption(renderLoading),
        scalesPageToFit: Js_undefined.fromOption(scalesPageToFit),
        startInLoadingState: Js_undefined.fromOption(startInLoadingState),
        domStorageEnabled: Js_undefined.fromOption(domStorageEnabled),
        javaScriptEnabled: Js_undefined.fromOption(javaScriptEnabled),
        mixedContentMode: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (contentMode) {
                    var to_string = function (param) {
                      if (param !== -853883856) {
                        if (param >= 422592140) {
                          return "never";
                        } else {
                          return "always";
                        }
                      } else {
                        return "compatibility";
                      }
                    };
                    return $$Array.of_list(List.map(to_string, contentMode));
                  }), mixedContentMode)),
        thirdPartyCookiesEnabled: Js_undefined.fromOption(thirdPartyCookiesEnabled),
        userAgent: Js_undefined.fromOption(userAgent),
        allowsInlineMediaPlayback: Js_undefined.fromOption(allowsInlineMediaPlayback),
        bounces: Js_undefined.fromOption(bounces),
        dataDetectorTypes: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (dataDetectorType) {
                    var to_string = function (param) {
                      if (param >= -922086728) {
                        if (param >= 4847905) {
                          if (param >= 487289268) {
                            return "address";
                          } else {
                            return "all";
                          }
                        } else if (param >= -119363460) {
                          return "calendarEvent";
                        } else {
                          return "none";
                        }
                      } else if (param >= -940571433) {
                        return "phoneNumber";
                      } else {
                        return "link";
                      }
                    };
                    return $$Array.of_list(List.map(to_string, dataDetectorType));
                  }), dataDetectorTypes)),
        decelerationRate: Js_undefined.fromOption(UtilsRN$BsReactNative.option_map((function (rate) {
                    var to_float = function (param) {
                      if (typeof param === "number") {
                        if (param >= 812216871) {
                          return 0.998;
                        } else {
                          return 0.99;
                        }
                      } else {
                        return param[1];
                      }
                    };
                    return $$Array.of_list(List.map(to_float, rate));
                  }), decelerationRate)),
        onShouldStartLoadWithRequest: Js_undefined.fromOption(onShouldStartLoadWithRequest),
        scrollEnabled: Js_undefined.fromOption(scrollEnabled)
      });
  var partial_arg$1 = ReactNative.WebView;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

function sourceUri(prim, prim$1, prim$2, prim$3, _) {
  var tmp = { };
  if (prim) {
    tmp.uri = prim[0];
  }
  if (prim$1) {
    tmp.method = prim$1[0];
  }
  if (prim$2) {
    tmp.headers = prim$2[0];
  }
  if (prim$3) {
    tmp.body = prim$3[0];
  }
  return tmp;
}

function sourceHtml(prim, prim$1, _) {
  var tmp = { };
  if (prim) {
    tmp.html = prim[0];
  }
  if (prim$1) {
    tmp.baseUrl = prim$1[0];
  }
  return tmp;
}

function contentInsets(prim, prim$1, prim$2, prim$3, _) {
  var tmp = { };
  if (prim) {
    tmp.top = prim[0];
  }
  if (prim$1) {
    tmp.left = prim$1[0];
  }
  if (prim$2) {
    tmp.bottom = prim$2[0];
  }
  if (prim$3) {
    tmp.right = prim$3[0];
  }
  return tmp;
}

function goForward(prim) {
  prim.goForward();
  return /* () */0;
}

function goBack(prim) {
  prim.goBack();
  return /* () */0;
}

function reload(prim) {
  prim.reload();
  return /* () */0;
}

function stopLoading(prim) {
  prim.stopLoading();
  return /* () */0;
}

exports.sourceUri = sourceUri;
exports.sourceHtml = sourceHtml;
exports.contentInsets = contentInsets;
exports.goForward = goForward;
exports.goBack = goBack;
exports.reload = reload;
exports.stopLoading = stopLoading;
exports.make = make;
/* ReasonReact Not a pure module */
