// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Interop from "./Interop";
import * as FlatList$ReactNative from "reason-react-native/src/components/FlatList.bs.js";
import * as Core from "@react-navigation/core";
import * as ScrollView$ReactNative from "reason-react-native/src/components/ScrollView.bs.js";
import * as SectionList$ReactNative from "reason-react-native/src/components/SectionList.bs.js";

var NavigationState = /* module */[];

function NavigationBase(M) {
  return /* module */[];
}

var Navigation = /* module */[];

var NavigationScene = /* module */[];

function t(prim) {
  return Interop.identity(prim[1]);
}

var HeaderTitle = /* module */[/* t */t];

var NavigationRouter = /* module */[];

var NavigationScreenProp = /* module */[];

var NavigationScreenProps = /* module */[];

var NavigationLayout = /* module */[];

var NavigationTransitionProps = /* module */[];

var NavigationTransitionSpec = /* module */[];

var TransitionConfig = /* module */[];

var NavigationScreenDetails = /* module */[];

function header(prim) {
  return Interop.identity(prim[1]);
}

function headerRenderItem(prim) {
  return Interop.identity(prim[1]);
}

var HeaderForceInset = /* module */[];

var ScreenOptions = /* module */[];

var StackNavigator = /* module */[/* ScreenOptions */ScreenOptions];

var SwitchNavigator = /* module */[];

var TabBar = /* module */[];

var DrawerIconProps = /* module */[];

var DrawerLabelProps = /* module */[];

var ContentComponent = /* module */[];

var ContentOptions = /* module */[];

function drawerIcon(prim) {
  return Interop.identity(prim[1]);
}

function drawerLabel(prim) {
  return Interop.identity(prim[1]);
}

var ScreenOptions$1 = /* module */[
  /* drawerIcon */drawerIcon,
  /* drawerLabel */drawerLabel
];

var DrawerNavigator = /* module */[
  /* ContentComponent */ContentComponent,
  /* ContentOptions */ContentOptions,
  /* ScreenOptions */ScreenOptions$1
];

var Material = /* module */[];

var Bottom = /* module */[];

var TabBarIconProps = /* module */[];

var TabBarLabelProps = /* module */[];

var TabScene = /* module */[];

var TabBarOnPress = /* module */[];

var TabBarOnLongPress = /* module */[];

var TabBarTopProps = /* module */[];

var BottomTabBarProps = /* module */[];

var TabBarTop = /* module */[];

var BottomTabBar = /* module */[];

function tabBarIcon(prim) {
  return Interop.identity(prim[1]);
}

function tabBarLabel(prim) {
  return Interop.identity(prim[1]);
}

var ScreenOptions$2 = /* module */[
  /* tabBarIcon */tabBarIcon,
  /* tabBarLabel */tabBarLabel
];

var TabNavigator = /* module */[
  /* Material */Material,
  /* Bottom */Bottom,
  /* TabBarIconProps */TabBarIconProps,
  /* TabBarLabelProps */TabBarLabelProps,
  /* TabScene */TabScene,
  /* TabBarOnPress */TabBarOnPress,
  /* TabBarOnLongPress */TabBarOnLongPress,
  /* TabBarTopProps */TabBarTopProps,
  /* BottomTabBarProps */BottomTabBarProps,
  /* TabBarTop */TabBarTop,
  /* BottomTabBar */BottomTabBar,
  /* ScreenOptions */ScreenOptions$2
];

var NavigationOptions = /* module */[
  /* Material */Material,
  /* Bottom */Bottom,
  /* TabBarIconProps */TabBarIconProps,
  /* TabBarLabelProps */TabBarLabelProps,
  /* TabScene */TabScene,
  /* TabBarOnPress */TabBarOnPress,
  /* TabBarOnLongPress */TabBarOnLongPress,
  /* TabBarTopProps */TabBarTopProps,
  /* BottomTabBarProps */BottomTabBarProps,
  /* TabBarTop */TabBarTop,
  /* BottomTabBar */BottomTabBar,
  /* ScreenOptions */ScreenOptions$2,
  /* tabBarIcon */tabBarIcon,
  /* tabBarLabel */tabBarLabel
];

var NavigationParams = /* module */[];

var AppContainer = /* module */[];

function Route(M) {
  var navigate = function (navigation) {
    navigation.navigate(M[/* routeName */0]);
    return /* () */0;
  };
  var navigateWithParams = function (navigation, params) {
    navigation.navigate(M[/* routeName */0], params);
    return /* () */0;
  };
  var getParams = function (navigation, param) {
    return navigation.state.params;
  };
  var NavigationActions = /* module */[];
  var NavigationContainer = /* module */[];
  return /* module */[
          /* navigate */navigate,
          /* navigateWithParams */navigateWithParams,
          /* getParams */getParams,
          /* NavigationActions */NavigationActions,
          /* NavigationContainer */NavigationContainer
        ];
}

function useNavigation(param) {
  return React.useContext(Core.NavigationContext);
}

var FlatList = /* module */[];

var ScrollView = /* module */[];

var SectionList = /* module */[];

var NavigationScreenPropsRec = /* () */0;

var NavigationScreenConfig = /* () */0;

var NavigationSceneRendererProps = 0;

export {
  NavigationState ,
  NavigationBase ,
  Navigation ,
  NavigationScene ,
  HeaderTitle ,
  NavigationRouter ,
  NavigationScreenProp ,
  NavigationScreenPropsRec ,
  NavigationScreenConfig ,
  NavigationScreenProps ,
  NavigationLayout ,
  NavigationTransitionProps ,
  NavigationTransitionSpec ,
  NavigationSceneRendererProps ,
  TransitionConfig ,
  NavigationScreenDetails ,
  header ,
  headerRenderItem ,
  HeaderForceInset ,
  StackNavigator ,
  SwitchNavigator ,
  TabBar ,
  DrawerIconProps ,
  DrawerLabelProps ,
  DrawerNavigator ,
  TabNavigator ,
  NavigationOptions ,
  NavigationParams ,
  AppContainer ,
  Route ,
  useNavigation ,
  FlatList ,
  ScrollView ,
  SectionList ,
  
}
/* react Not a pure module */
