// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function nullableToOption(stringOrNull) {
  return Promise.resolve(stringOrNull === null ? undefined : Caml_option.some(stringOrNull));
}

export {
  nullableToOption ,
  
}
/* No side effect */
