// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE


function test(param) {
  return (function (prim) {
      return /* () */0;
    });
}

export {
  test ,
  
}
/* No side effect */
